version: "3.8"

services:
  whatsup:
    image: whatsup
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  server-backend:
    image: server-backend
    ports: 
      - "5001:5001"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge