version: "3.8"

services:
  app-frontend:
    image: app-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  app-backend:
    image: app-backend
    ports: 
      - "5001:5001"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge